# docker 이미지로 만들 운영서버 DB 정(아직 관리방법 안정해서 git ignore)
spring:
  jpa:
#    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#      hibernate:
#        format_sql: true
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:mariadb://dreambody.cec96arowffv.ap-northeast-2.rds.amazonaws.com:3306/dreambody
    driver-class-name: org.mariadb.jdbc.Driver
    username: monkeyDugi
    password: qhtnddl!1